### ISSUE TITLE
20171130 Microservices in Golang - part 3 - docker-compose and datastores

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#113]
标题：Microservices in Golang - part 3 - docker-compose and datastores

原文链接：https://ewanvalentine.io/microservices-in-golang-part-3/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://ewanvalentine.io/microservices-in-golang-part-3/

作者：[Ewan Valentine](http://ewanvalentine.io/author/ewan)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by rxcai** [comment]
I'll take it

**Comment by polaris1119** [comment]
在你的辛苦校对下，校对进度赶上来了~ 👏

**Comment by rxcai** [comment]
是大家的努力，然后现在要鼓励大家翻译了 ;)

**Comment by polaris1119** [comment]
@rxcai 可以考虑优先把这篇搞定。 😆

**Comment by rxcai** [comment]
@polaris1119  在进行中，但是最近时间比较零碎。。。

**Comment by rxcai** [comment]
上周出去玩 这周事情多 争取周六搞定这篇文章！

**Comment by zhangyang9** [comment]
我来翻译吧
标题：Microservices in Golang - part 3 - docker-compose and datastores

原文链接：https://ewanvalentine.io/microservices-in-golang-part-3/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

----------------

via: https://ewanvalentine.io/microservices-in-golang-part-3/

作者：[Ewan Valentine](http://ewanvalentine.io/author/ewan)
译者：[zhangyang9](https://github.com/zhangyang9)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出

**Comment by polaris1119** [comment]
以后只需要加上：我来翻译 就行，后面一堆不需要复制。呵呵

**Comment by zhangyang9** [comment]
翻译完成 + Microservices in Golang - part 3 - docker-compose and datastores
