### ISSUE TITLE
20171202 How to add a GUI to your Golang app in 5 easy steps (powered by Electron)

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#118]
# How to add a GUI to your Golang app in 5 easy steps (powered by Electron)

原文链接：https://medium.com/@social_57971/how-to-add-a-gui-to-your-golang-app-in-5-easy-steps-c25c99d4d8e0

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://medium.com/@social_57971/how-to-add-a-gui-to-your-golang-app-in-5-easy-steps-c25c99d4d8e0

作者：[Asticode](https://medium.com/@social_57971)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by fengchunsgit** [comment]
me

**Comment by fengchunsgit** [comment]
https://github.com/fengchunsgit/GCTT/commit/3ecb3d98b21768f6992b431b163a5140bab8c406

**Comment by polaris1119** [comment]
@rxcai 他可能没有关闭的权限，提交 PR 后，咱们关闭就行。 @fengchunsgit 得发起 PR。

**Comment by rxcai** [comment]
close since pr #127 created.
