### ISSUE TITLE
20190515 Garbage Collection In Go : Part II - GC Traces

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1215]
标题：Garbage Collection In Go : Part II - GC Traces

原文链接：https://www.ardanlabs.com/blog/2019/05/garbage-collection-in-go-part2-gctraces.html

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

---

via: https://www.ardanlabs.com/blog/2019/05/garbage-collection-in-go-part2-gctraces.html

作者：[William Kennedy](https://github.com/ardanlabs)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出

**Comment by tpkeeper** [comment]
申请翻译

**Comment by magichan** [comment]
@tpkeeper 这是系列的第二篇，因此建议读一读第一篇 #1216 。
