### ISSUE TITLE
20190515 Garbage Collection In Go : Part I - semantics

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1216]
标题：Garbage Collection In Go : Part I - semantics

原文链接：https://www.ardanlabs.com/blog/2018/12/garbage-collection-in-go-part1-semantics.html

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

via: https://www.ardanlabs.com/blog/2018/12/garbage-collection-in-go-part1-semantics.html

作者：William Kennedy
译者：译者ID
校对：校对者ID

本文由 GCTT 原创编译，Go 中文网 荣誉推出

**Comment by LSivan** [comment]
认领
