### ISSUE TITLE
20190523 Go is Google's language, not ours

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1227]
标题：Golang  是谷歌的语言，不是我们的

原文链接：https://utcc.utoronto.ca/~cks/space/blog/programming/GoIsGooglesLanguage

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

---

via: https://utcc.utoronto.ca/~cks/space/blog/programming/GoIsGooglesLanguage

作者：[Chris Siebenmann](https://utcc.utoronto.ca/~cks/)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出

**Comment by carsickcars** [comment]
申请翻译
