### ISSUE TITLE
20190527 GO MEMORY MANAGEMENT - Part2

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#1249]
标题：GO MEMORY MANAGEMENT - Part2

原文链接：https://povilasv.me/go-memory-management-part-2/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---

via: https://povilasv.me/go-memory-management-part-2/

作者：[Povilas](https://povilasv.me/about/)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by stonelgh** [comment]
由于 QQ 群已满，入群失败。看了看该系列的三篇文章，虽然有些文不对题（只有第一篇与 Go 内存管理相关的内容多一些），但读来对开阔眼界还是有好处的，所以就试着翻译了一下，并创建了一个 [PR #1296](https://github.com/studygolang/GCTT/pull/1296)。这样做实属不得已，但确乎有悖组织程序，不知道能不能合并。
