### ISSUE TITLE
20150606 Handling 1 Million Requests per Minute with Golang

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#1251]
标题：Handling 1 Million Requests per Minute with Golang

原文链接：http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---

via: http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/

作者：[Marcio Castilho](https://medium.com/@mcastilho)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by TomatoAres** [comment]
在go语言中文网看到了相同文章翻译：[[译]使用Go处理每分钟百万请求](https://studygolang.com/articles/21604?utm_campaign=studygolang.com&utm_source=studygolang&utm_medium=email)

**Comment by magichan** [comment]
已存在译文，关闭该 issue。
