### ISSUE TITLE
20190612 Go: What is the Unsafe Package?

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#1276]
标题：Go: What is the Unsafe Package?

原文链接：https://medium.com/@blanchon.vincent/go-what-is-the-unsafe-package-d2443da36350

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---

via: https://medium.com/@blanchon.vincent/go-what-is-the-unsafe-package-d2443da36350

作者：[Vincent Blanchon](https://medium.com/@blanchon.vincent)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by MLittleToo** [comment]
我来翻译

**Comment by watermelo** [comment]
@BeGemini 同学有没有开始翻译，如果没有的话。我这边有一个翻译已经完成了。

**Comment by BeGemini** [comment]
那你提交了吧，我这边刚开始

Sent from my iPhone

On Jun 26, 2019, at 12:08 PM, watermelon <notifications@github.com<mailto:notifications@github.com>> wrote:


@BeGemini<https://github.com/BeGemini> 同学有没有开始翻译，如果没有的话。我这边有一个翻译已经完成了。

**Comment by watermelo** [comment]
@BeGemini 好
