### ISSUE TITLE
20190705 Do you really need microservices?

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1298]
标题：Do you really need microservices?

原文链接：https://itnext.io/do-you-really-need-microservices-e85d7711c78b?gi=8234cdf42ea6

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

via: https://medium.com/@madhukaudantha/microservice-architecture-and-design-patterns-for-microservices-e0e5013fd58a

作者：browserlondon https://itnext.io/@browserlondon
译者：译者ID
校对：校对者ID

本文由 GCTT 原创编译，Go 中文网 荣誉推出

**Comment by Alex1996a** [comment]
申请翻译
