### ISSUE TITLE
apply for two articles not listed in issues to translate

### ISSUE THREAD

**Issue by DoubleLuck** [studygolang/GCTT#1320]
There is a series of three articles talking about map in Go, first of which is already listed in [issues](https://github.com/studygolang/GCTT/issues/1303)  and I've done translation. 
But the other two haven't been listed in issues. 
I'm interested in map in Go and want to translate [Part II](https://medium.com/@blanchon.vincent/go-map-design-by-code-part-ii-50d111557c08) and [Part III](https://medium.com/@blanchon.vincent/go-concurrency-access-with-maps-part-iii-8c0a0e4eb27e) .
Please allow me to do this.

**Comment by polaris1119** [comment]
OK 

see #1321 #1322
