### ISSUE TITLE
20190717 The cost of syntactic sugar in Go

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1324]
标题：The cost of syntactic sugar in Go

原文链接：https://medium.com/@asilvr/the-cost-of-syntactic-sugar-in-go-5aa9dc307fe0

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

---
via: https://medium.com/@asilvr/the-cost-of-syntactic-sugar-in-go-5aa9dc307fe0

作者：[Alex Silver](https://medium.com/@asilvr)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出

**Comment by Alex1996a** [comment]
申请翻译
