### ISSUE TITLE
20190725 Writing delightful HTTP middleware in Go

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1333]
标题：Writing delightful HTTP middleware in Go

原文链接：https://doordash.engineering/2019/07/22/writing-delightful-http-middlewares-in-go/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

via: https://doordash.engineering/2019/07/22/writing-delightful-http-middlewares-in-go/

作者：Zohaib Sibte Hassan https://doordash.engineering/author/zohaibsibtehassan/
译者：译者ID
校对：校对者ID

本文由 GCTT 原创编译，Go 中文网 荣誉推出

**Comment by Alex1996a** [comment]
申请翻译
