### ISSUE TITLE
20190725 Go: Finalizers

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1334]
标题：Go: Finalizers

原文链接：https://medium.com/@blanchon.vincent/go-finalizers-786df8e17687

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

via: https://medium.com/@blanchon.vincent/go-finalizers-786df8e17687
作者：Vincent Blanchon https://medium.com/@blanchon.vincent 
译者：译者ID
校对：校对者ID

本文由 GCTT 原创编译，Go 中文网 荣誉推出

**Comment by Maple24** [comment]
申请翻译
