### ISSUE TITLE
20190725 Deploy a Golang App in 5 Minutes.

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1335]
标题：Deploy a Golang App in 5 Minutes.

原文链接：https://medium.com/@monirz/deploy-golang-app-in-5-minutes-ff354954fa8e

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

via:https://medium.com/@monirz/deploy-golang-app-in-5-minutes-ff354954fa8e
作者：Monir Zaman https://medium.com/@monirz
译者：译者ID
校对：校对者ID

本文由 GCTT 原创编译，Go 中文网 荣誉推出

**Comment by maxwellhertz** [comment]
申请翻译
