### ISSUE TITLE
20190707 Go: Unknown Parts of the Test Package

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#1356]
标题：Go: Unknown Parts of the Test Package

原文链接：https://medium.com/@blanchon.vincent/go-unknown-parts-of-the-test-package-df8988b2ef7f

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---

via: https://medium.com/@blanchon.vincent/go-unknown-parts-of-the-test-package-df8988b2ef7f

作者：[Vincent Blanchon](https://medium.com/@blanchon.vincent)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by sammyne** [comment]
我来翻译~ @polaris1119

**Comment by sammyne** [comment]
请问原文“Report your custom metrics”节个人理解和相应的代码不符，且代码跑不通这个改如何是好= = @polaris1119

**Comment by polaris1119** [comment]
这是 1.13 增加的功能，所以，需要升级到 1.13 beta 版本

**Comment by sammyne** [comment]
我有用1.13版的，具体是golang:1.13-rc-buster

错误提示是无法将`bool`转为`int`，所以，结合原文的描述，我理解是作者更新的了`Deck`结构体的函数，但是没贴出来，所以采用原始的`Deck`代码时就报错了。在原文下的评论也还没得到作者的回复~

**Comment by polaris1119** [comment]
可以考虑按你的方式来修正，保证正常编译，然后备注说明

**Comment by sammyne** [comment]
ok @polaris1119
