### ISSUE TITLE
20190807 Vuejs + Golang = A rare combination

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1374]
标题：Vuejs + Golang = A rare combination

原文链接：https://medium.com/@adeshg7/vuejs-golang-a-rare-combination-53538b6fb918

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

---

via: https://medium.com/@adeshg7/vuejs-golang-a-rare-combination-53538b6fb918

作者：[Adesh Gautam](https://medium.com/@adeshg7)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出

**Comment by M1seRy** [comment]
认领。这篇我带走了。对Vue.js比较熟悉，估计翻译起来顺利一点。

**Comment by M1seRy** [comment]
@polaris1119 已完成翻译部分，待校验。[#1389 ](https://github.com/studygolang/GCTT/pull/1389)

**Comment by M1seRy** [comment]
时间挺久了，后续没人校验吗？这是啥情况？
