### ISSUE TITLE
20190820 Modern garbage collection

### ISSUE THREAD

**Issue by meission** [studygolang/GCTT#1391]
标题：Modern garbage collection

原文链接：https://blog.plan99.net/modern-garbage-collection-911ef4f8bd8e?gi=90cab303c568

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

---

via: https://blog.plan99.net/modern-garbage-collection-911ef4f8bd8e?gi=90cab303c568

作者：[Mike Hearn](https://blog.plan99.net/@octskyward)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygola

**Comment by TomatoAres** [comment]
我来翻译

**Comment by TomatoAres** [comment]
已发布，需关闭
