### ISSUE TITLE
认领翻译任务

### ISSUE THREAD

**Issue by yangshun2005** [studygolang/GCTT#1437]
认领golang翻译任务

**Comment by TomatoAres** [comment]
[认领流程](https://github.com/studygolang/GCTT/wiki/03-%E6%96%B0%E7%9A%84%E9%80%89%E9%A2%98%E5%92%8C%E7%BF%BB%E8%AF%91%E8%AE%A4%E9%A2%86%E6%96%B9%E5%BC%8F)
