### ISSUE TITLE
20191125 Go: Goroutine, OS Thread and CPU Management

### ISSUE THREAD

**Issue by watermelo** [studygolang/GCTT#1498]
https://medium.com/a-journey-with-go/go-goroutine-os-thread-and-cpu-management-2f5a5eaf518a

标题：Go: Goroutine, OS Thread and CPU Management

原文链接：https://medium.com/a-journey-with-go/go-goroutine-os-thread-and-cpu-management-2f5a5eaf518a

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---

via: https://medium.com/a-journey-with-go/go-goroutine-os-thread-and-cpu-management-2f5a5eaf518a

作者：[Vincent Blanchon](https://medium.com/@blanchon.vincent)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by lxbwolf** [comment]
我来翻译
