### ISSUE TITLE
20191203 微软系统设计模式之 Cache-Aside Pattern

### ISSUE THREAD

**Issue by watermelo** [studygolang/GCTT#1509]
https://docs.microsoft.com/zh-cn/previous-versions/msp-n-p/dn589799(v=pandp.10)

标题：Cache-Aside Pattern

原文链接：https://docs.microsoft.com/zh-cn/previous-versions/msp-n-p/dn589799(v=pandp.10)

本文是微软系统设计模式的第 1 篇--缓存设计 Cache-Aside 模式，共计 24 篇，均为常见的系统设计模式，比较有意思可以先尝试翻译翻译，例子是 C# 语言的，如果能转成 Go 是最好了，可以新建一个目录单独存储这一系列。

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---

https://docs.microsoft.com/zh-cn/previous-versions/msp-n-p/dn589799(v=pandp.10)

作者：[Design Patterns ](https://docs.microsoft.com/zh-cn/previous-versions/msp-n-p/dn600223(v=pandp.10))
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by weibobo** [comment]
https://blog.csdn.net/ethanwhite/category_9267561.html
看上去已经有人翻译了

**Comment by weibobo** [comment]
https://github.com/SapphireWriter/Cloud-Design-Patterns

**Comment by watermelo** [comment]
> https://blog.csdn.net/ethanwhite/category_9267561.html
> 看上去已经有人翻译了

收到～
