### ISSUE TITLE
20190602 Go: How Does the Goroutine Stack Size Evolve?

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#1632]
标题：Go: How Does the Goroutine Stack Size Evolve?

原文链接：https://medium.com/a-journey-with-go/go-how-does-the-goroutine-stack-size-evolve-447fc02085e5

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---
via: https://medium.com/a-journey-with-go/go-how-does-the-goroutine-stack-size-evolve-447fc02085e5

作者：[Vincent Blanchon](https://medium.com/@blanchon.vincent)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by Jun10ng** [comment]
我来翻译。

此外，我想推荐一个国外博主：https://dave.cheney.net/category/golang，如果可以的话，我将翻译他的部分文章，实际上我已经翻译了几篇：https://github.com/Jun10ng/go_blog_translation/blob/master/Dave%E5%8D%9A%E5%AE%A2%E7%BF%BB%E8%AF%91/Dave%20%E5%8D%9A%E5%AE%A2%E7%BF%BB%E8%AF%91%E8%AE%A1%E5%88%92.md

**Comment by polaris1119** [comment]
@Jun10ng 当然可以，实际上它的文章经常被选，很多都佷棒。欢迎 提 PR。

**Comment by Jun10ng** [comment]
> @Jun10ng 当然可以，实际上它的文章经常被选，很多都佷棒。欢迎 提 PR。

好的，我按照GTCC的格式修改下，再看看有无重复文章。
