### ISSUE TITLE
20200329 Memory Leaking Scenarios

### ISSUE THREAD

**Issue by watermelo** [studygolang/GCTT#1655]
标题：Memory Leaking Scenarios

原文链接：https://go101.org/article/memory-leaking.html

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

---
```
via: https://go101.org/article/memory-leaking.html

作者：[go101](https://go101.org/)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com)
```

**Comment by polaris1119** [comment]
go 101 是国人写的，他中英文都有。中文我做了一个镜像。 http://go101.studygolang.com/article/memory-leaking.html

**Comment by watermelo** [comment]
> go 101 是国人写的，他中英文都有。中文我做了一个镜像。 http://go101.studygolang.com/article/memory-leaking.html

ok
