### ISSUE TITLE
20200821 Avoid using golang http.DefaultServerMux for production servers

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#1811]
标题：Avoid using golang http.DefaultServerMux for production servers

原文链接：https://sgrodriguez.github.io/2020/08/21/defaultServerMux.html

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---
via: https://sgrodriguez.github.io/2020/08/21/defaultServerMux.html

作者：[Santiago Rodriguez](https://sgrodriguez.github.io/about.html)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by TomatoAres** [comment]
我来翻译

**Comment by double12gzh** [comment]
> 我来翻译

如果有需要，您可以参考一下这篇文章：https://zhuanlan.zhihu.com/p/212459432，这篇文章翻译的并不是很地道，仅供参考。

**Comment by TomatoAres** [comment]
> > 我来翻译
> 
> 如果有需要，您可以参考一下这篇文章：[https://zhuanlan.zhihu.com/p/212459432，这篇文章翻译的并不是很地道，仅供参考。](https://zhuanlan.zhihu.com/p/212459432%EF%BC%8C%E8%BF%99%E7%AF%87%E6%96%87%E7%AB%A0%E7%BF%BB%E8%AF%91%E7%9A%84%E5%B9%B6%E4%B8%8D%E6%98%AF%E5%BE%88%E5%9C%B0%E9%81%93%EF%BC%8C%E4%BB%85%E4%BE%9B%E5%8F%82%E8%80%83%E3%80%82)

404 了
