### ISSUE TITLE
20171223 Go Reflection: Creating Objects from Types — Part II (Composite Types)

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#213]
标题：Go Reflection: Creating Objects from Types — Part II (Composite Types)

原文链接：https://medium.com/kokster/go-reflection-creating-objects-from-types-part-ii-composite-types-69a0e8134f20

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://medium.com/kokster/go-reflection-creating-objects-from-types-part-ii-composite-types-69a0e8134f20

作者：[Sidhartha Mani](https://medium.com/@utter_babbage)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by MaleicAcid** [comment]
申请翻译

**Comment by ParadeTo** [comment]
认领

**Comment by ParadeTo** [comment]
@polaris1119

**Comment by yiyulantian** [comment]
@ParadeTo  我在翻译 part I 时，里面出现一些作者自己约定的术语，例如：
In order to create an object from a type signature, both the type and kind of the object are necessary. **Henceforth, when I use the term ‘type signature’, I mean Golang’s reflect.Type object for that type.**

我看在 part II 中也有出现，在这里提一下，希望对你有帮助～

**Comment by polaris1119** [comment]
@yiyulantian 给力啊

**Comment by ParadeTo** [comment]
@yiyulantian 多谢提醒，其实我是打算看完你的那篇后再翻译的

**Comment by polaris1119** [comment]
@ParadeTo 那篇已经校对完成，争取今天发布
