### ISSUE TITLE
20171219 Aspects of a good Go library

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#233]
标题：Aspects of a good Go library

原文链接：https://medium.com/@cep21/aspects-of-a-good-go-library-7082beabb403

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://medium.com/@cep21/aspects-of-a-good-go-library-7082beabb403

作者：[Jack Lindamood](https://medium.com/@cep21)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by ictar** [comment]
认领~

**Comment by rxcai** [comment]
how "old" are u @ictar bravo!

**Comment by ictar** [comment]
@rxcai It's not gentle to ask a lady her age : )

**Comment by rxcai** [comment]
@ictar  哈哈，好像没有被你get到笑点，可以理解为 “怎么老是你”，不会有代沟吧。。。

**Comment by ictar** [comment]
@rxcai 嘿嘿，默默笑了一分钟…… 不要介意“老”是我哈 ^ _ ^

**Comment by rxcai** [comment]
@ictar 深表感谢 咋会介意 ;)

**Comment by ictar** [comment]
@rxcai 翻译完了，请审阅 o(*￣︶￣*)o：https://github.com/studygolang/GCTT/pull/250
