### ISSUE TITLE
20171229 Microservices in Golang - Part 5 - Event brokering with Go Micro

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#257]
标题：Microservices in Golang - Part 5 - Event brokering with Go Micro

原文链接：https://ewanvalentine.io/microservices-in-golang-part-5/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://ewanvalentine.io/microservices-in-golang-part-5/

作者：[André Carvalho](https://ewanvalentine.io/microservices-in-golang-part-5/)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by ArisAries** [comment]
认领。

**Comment by zhangyang9** [comment]
zhangyang9认领

标题：Microservices in Golang - Part 5 - Event brokering with Go Micro

原文链接：https://ewanvalentine.io/microservices-in-golang-part-5/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

----------------

via: https://ewanvalentine.io/microservices-in-golang-part-5/

作者：[André Carvalho](https://ewanvalentine.io/microservices-in-golang-part-5/)
译者：[zhangyang9](https://github.com/zhangyang9)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出

**Comment by shniu** [comment]
翻译 by shniu
