### ISSUE TITLE
20170612 Golang Pros and Cons for DevOps (Part 2 of 6): Interface Implementation and Public/Private Designations

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#308]
标题：Golang Pros and Cons for DevOps (Part 2 of 6): Interface Implementation and Public/Private Designations

原文链接：https://blog.bluematador.com/posts/golang-pros-cons-for-devops-part-2/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://blog.bluematador.com/posts/golang-pros-cons-for-devops-part-2/

作者：[Matthew Barlocker](https://github.com/mbarlocker)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go中文网](https://studygolang.com/) 荣誉推出
```

**Comment by xiaolajiccc** [comment]
我想认领这篇文章

**Comment by UnFat** [comment]
翻译稿[Go 在 DevOps 中的优势与劣势（六篇系列文章之二）：接口实现和公共:私有指定。.zip](https://github.com/studygolang/GCTT/files/1801828/Go.DevOps.zip)

**Comment by UnFat** [comment]
#308 【翻译完成】Golang Pros and Cons for DevOps (Part 2 of 6): Interface Implementation and Public/Private Designations

**Comment by xen0n** [comment]
这不是 PR。。。需要使用 Git 工具或者 GitHub web 界面做 commit 并且提交
