### ISSUE TITLE
【选题】Go Defer Simplified with Practical Visuals

### ISSUE THREAD

**Issue by shockw4ver** [studygolang/GCTT#45]
原文链接：[Go Defer Simplified with Practical Visuals](https://blog.learngoprogramming.com/golang-defer-simplified-77d3b2b817ff)

作者：[Inanc Gumus](https://blog.learngoprogramming.com/golang-defer-simplified-77d3b2b817ff)
选题：[shockw4ver](https://github.com/shockw4ver)

**Comment by polaris1119** [comment]
已加入
