### ISSUE TITLE
20180318 How to sign messages in Java and verify in Go

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#458]
标题：How to sign messages in Java and verify in Go

原文链接：https://mhmxs.blogspot.com/2018/03/how-to-sign-messages-in-java-and-verify.html

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://mhmxs.blogspot.com/2018/03/how-to-sign-messages-in-java-and-verify.html

作者：[mhmxs](https://mhmxs.blogspot.com/)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by fredvence** [comment]
认领

**Comment by fredvence** [comment]
@krystollia 这篇文章早就翻译好了，不需要在翻译了， 好像只是merge了没有发布。。麻烦组长处理下
@polaris1119 
https://github.com/studygolang/GCTT/pull/465

**Comment by polaris1119** [comment]
@fredvence 好的，可能遗漏了，感谢提醒

**Comment by polaris1119** [comment]
确认，之前就发布了，不好意思。漏了。 https://studygolang.com/articles/12701
