### ISSUE TITLE
20180325 7 notes about strings.builder in Golang

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#493]
标题：7 notes about strings.builder in Golang

原文链接：https://medium.com/@thuc/8-notes-about-strings-builder-in-golang-65260daae6e9

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://medium.com/@thuc/8-notes-about-strings-builder-in-golang-65260daae6e9

作者：[Thuc Le](https://medium.com/@thuc)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by alfred-zhong** [comment]
@polaris1119 翻译认领

**Comment by alfred-zhong** [comment]
@polaris1119 这篇文章出错了，我已经让原作者改过来了。文章标题也改成了 “7 notes about strings.builder in Golang”。

这个 issue 标题我也就自己修改了。
