### ISSUE TITLE
20180518 A Step-by-Step Guide to Go Internationalization (i18n) & Localization (l10n)

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#634]
标题：A Step-by-Step Guide to Go Internationalization (i18n) & Localization (l10n)

原文链接：https://dev.to/theodesp/a-step-by-step-guide-to-go-internationalization-i18n--localization-l10n-4ig2

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://dev.to/theodesp/a-step-by-step-guide-to-go-internationalization-i18n--localization-l10n-4ig2

作者：[theodesp profile image Theofanis Despoudis](https://dev.to/theodesp)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by huasheng28** [comment]
我来翻译
---
另外你的原文链接当中也有一个原文链接
https://phraseapp.com/blog/posts/internationalization-i18n-go/
