### ISSUE TITLE
20161013 Panicking like a Gopher

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#642]
标题：Panicking like a Gopher

原文链接：https://medium.com/golangspec/panicking-like-a-gopher-367a9ce04bb8

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
----------------

via: https://medium.com/golangspec/panicking-like-a-gopher-367a9ce04bb8

作者：[Michał Łowicki](https://medium.com/@mlowicki)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by Yousanflics** [comment]
2016/9/26 Go中的“简单陈述”概念.md


  Go中的“简单陈述”概念
  =======
  在Golang[规范](https://golang.org/ref/spec)中有一个术语简单陈述， 这个在整个文档中可能不常使用但Go的语法只允许在几个重要的地方使用这些陈述。这篇短文的目的是介绍简单陈述和可以使用它的地方。
![](https://cdn-images-1.medium.com/max/1600/1*Sh2PTmHloYTNWptEXj4FrA.jpeg)
Photography: Ursula Coyote / Netflix

在规范文档中术语的简单陈述被[SimpleStmt](https://golang.org/ref/spec#Statements)的产生（使用[EBNF](https://golang.org/ref/spec#Notation)）所定义：
```go
SimpleStmt = EmptyStmt | ExpressionStmt | SendStmt | IncDecStmt | Assignment | ShortVarDecl .
```
让我们通过介绍6中简单的陈述来开始吧
  ### 1. 空白声明
  很自然的可以知道在被标记为“simple statements”的jar中声明肯定什么都不会做
  ### 2.增加或减少声明
```go
x++  // 语义上等价于赋值x + = 1
x--  // x -= 1
```
在Go中，在表达式操作数后用“- -”或“++”符号表示的构造并不是一个表达式，所以你在源文件中的.go拓展中看不到像下面这样纠结的创作，如：
```go
foo = bar++ + 10
```
尽管这是一个声明，但因为它是简单的声明所以可以用有意义的地方并且不会在不应该的地方引入不必要的负担（通过使代码难以阅读和难以维护）。

_**在Golang中没有前缀版本，即在操作数之前放置“ - ”或“++”**。_
  ### 3.发送声明
词汇标记“< - ”表示通过频道发送值。它不返回任何值因此不需要表达它。
  ### 4.表达声明
某些表达式可以放入需要声明的地方。
_**块是由大括号括起来的一系列语句，例如，表达式语句在这种情况下完全有效。**_
允许的选项是：
- 函数调用（除了一些内置函数，例如append，cap，complex，imag，len，make，new，real，unsafe.Alignof，unsafe.Offsetof和unsafe.sizeOf）
- 方法调用
- 接收操作符
```go
func (s S) m() {
    fmt.Printf("Hi %s\n", s.name)
}
func f(n int) {
    fmt.Printf("f says %d\n", n)
}

func main() {
    f(1)
    s := S{"Michał"}
    s.m()
    c := make(chan int)
    go func() {
        c <- 1
    }()
    <-c
    numbers := []int{1, 2, 3}
    len(numbers)  // error: len(numbers) evaluated but not used
}
```
  ### 5. Assignment
Assignment in the most basic form should be well known. Declared variable is needed and right-hand expression must be [assignable](https://medium.com/golangspec/assignability-in-go-27805bcd5874) to a variable:
```go
var population int64
population = 8000000 // assignment
var city, country string
// assignment of two single-value expressions to two variables
city, country = "New York", "USA"
```
 When it goes to assigning more than one value to a list of variables there’re two forms. In the first one there is a single expression returning multiple values like e.g. function call:
```go
f := func() (int64, string) {
    return 2000000, "Paris"
}
var population int64
var city string
population, city = f()
```  
Second form encompasses many expressions on the right side but each one is single-valued:
```
population, city = 13000000, "Tokyo"
```
population, city = 13000000, "Tokyo"
```
f := func() (int64, string) {
    return 4000000, "Sydney"
}
var population int64
var city, country string
population, city, country = f(), "Australia"
```
as it throws “multiple-value f() in single-value context” while compilation.

An assignment operation is a construct assembled from “=” sign preceded by one of the binary operators:

- addition (+)
- subtraction (-)
- bitwise OR (|)
- bitwise XOR (^)
- multiplication (*)
- division (/)
- modulo (%)
- bitwise left and right shift (<< and >>)
- bitwise AND (&)
- bit clear (&^)
a op= b is semantically equivalent to a = a op b but a is evaluated only once. Assignment operation is also valid assignment statement.

### 6. Simple variable declaration
It’s a shorthand for regular variable declaration where initializer is required. Moreover type which isn’t explicitly specified is inferred from initializer’s type:
```go
s := S{}
a := [...]int{1,2,3}
one, two := f(), g()
```
It’s clear now what constitutes set of valid simple statements. But where are they applicable?
### **If statement**
Simple statement can be optionally placed before condition expression. It’s used quite often to declare variable (using short variable declaration), used later inside expression:
```go
gen := func() int8 {
    return 10
}
if num := gen(); num > 5 {
    fmt.Printf("%d is greater than 5\n", num)
}
```
### For statement
Init or post statements in for clause can be only simple statements. Common use case is to have short variable declaration as init statement and either assignment operation or increment / decrement statement:
```go
for i := 0; i < 10; i += 1 {
    fmt.Println(i)
}
```
Nothing stops programmer though from using other simple statements there.
### Switch statement
In a similar way as with if statement it’s allowed to put optional simple statement before expression in [expression switch](https://golang.org/ref/spec#Expression_switches) :
```go
switch aux := 2; letter {
case 'a':
    fmt.Println(aux)
case 'b':
    fmt.Println(aux << 1)
case 'c':
    fmt.Println(aux << 2)
default:
    fmt.Println("no match")
}
```
or in front of guard in [type switch](https://golang.org/ref/spec#Type_switches):
```go
type I interface {
    f(num int8) int8
}
type T1 struct{}
func (t T1) f(num int8) int8 {
    return 1
}
type T2 struct{}
func (t T2) f(num int8) int8 {
    return 2
}
...
var i I = T1{}
switch aux := 10; val := i.(type) {
case nil:
    fmt.Printf("nil %T %d\n", val, aux)
case T1:
    fmt.Printf("T1 %T %d\n", val, aux)
case T2:
    fmt.Printf("T2 %T %d\n", val, aux)
}
```
which outputs:
```go
T1 main.T1 10
```

  

  
  

  --------------------------------------------------------------------------------
  
  via: [原文地址](https://medium.com/golangspec/simple-statement-notion-in-go-b8afddfc7916)
  
  作者：[Michał Łowicki](https://medium.com/@mlowicki)
  译者：[yousanflics](https://github.com/yousanflics)
  校对：[校对者ID](https://github.com/校对者ID)
  
  本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go中文网](https://studygolang.com/) 荣誉推出

**Comment by fredvence** [comment]
认领~  好久没来了0.0

**Comment by yixiaoer** [comment]
认领
