### ISSUE TITLE
20181010 Goroutine Scoped Context Proposal

### ISSUE THREAD

**Issue by polaris1119** [studygolang/GCTT#862]
标题：Goroutine Scoped Context Proposal

原文链接：https://posener.github.io/goroutine-scoped-context/

译者自己根据原文翻译，译文保存为 markdown 格式，并附上尾部的签名。

```
---

via: https://posener.github.io/goroutine-scoped-context/

作者：[Eyal Posener](https://posener.github.io/)
译者：[译者ID](https://github.com/译者ID)
校对：[校对者ID](https://github.com/校对者ID)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

**Comment by alfred-zhong** [comment]
@polaris1119 翻译认领。上周看过这篇，我来吧。

**Comment by alfred-zhong** [comment]
@polaris1119 这篇文章里作者后来承认自己的这个提案是有问题的，又写了一篇 [Go Context Scoping Part 2](https://posener.github.io/context-scoping/)。
所以你看这篇是不是先搁置一下，提案本身还是有漏洞。

**Comment by alfred-zhong** [comment]
@polaris1119 关注一下。这篇文章是否暂时搁置？
