### ISSUE TITLE
【选题】Ultimate Guide to Go Variadic Functions

### ISSUE THREAD

**Issue by shockw4ver** [studygolang/GCTT#89]
原文链接：https://blog.learngoprogramming.com/golang-variadic-funcs-how-to-patterns-369408f19085

作者：[Inanc Gumus](https://blog.learngoprogramming.com/@inanc?source=post_header_lockup)
选题：[shockw4ver](https://github.com/shockw4ver)

**Comment by polaris1119** [comment]
已加入 https://github.com/studygolang/GCTT/blob/master/sources/tech/20171102%20Ultimate%20Guide%20to%20Go%20Variadic%20Functions.md
