### ISSUE TITLE
关于官方博客2014/08/25文章的翻译

### ISSUE THREAD

**Issue by hirorogithub** [studygolang/GCTT#93]
http://blog.csdn.net/qq_24328101/article/details/78700847#官方blog翻译
偶然发现这个翻译组,前两天兴趣使然翻译了这篇,水平有限,如果你们用得上也请拿去

**Comment by rxcai** [comment]
@hirorogithub  非常棒呀，能否烦请根据我们的 [翻译流程](https://github.com/studygolang/GCTT/wiki/02-%E7%BF%BB%E8%AF%91%E6%B5%81%E7%A8%8B) 和 [排版指南](https://github.com/studygolang/GCTT/blob/master/%E4%B8%AD%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8C%97.md) 提交pr？

**Comment by polaris1119** [comment]
@hirorogithub 能否参与进来一起搞呢？

**Comment by hirorogithub** [comment]
@polaris1119 抱歉估计我业余时间并不是很充裕，希望日后有机会一起为社区贡献
@rxcai ok，但是可能需要过一段时间，因为接下来可能我没有太多时间。。。如果你们打算直接拿去改排版校正了也OK，我就不重复工作了
